name: shvirtd-project

include:
  - proxy.yaml

# networks:
#   backend:
#     driver: bridge
#     ipam:
#       config:
#         - subnet: 172.20.0.0/16

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: app_web
    restart: always
    networks:
      backend:
        ipv4_address: 172.20.0.5
    environment:
      DB_HOST: db
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}

  db:
    image: mysql:8
    container_name: app_db
    restart: always
    networks:
      backend:
        ipv4_address: 172.20.0.10
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql


volumes:
  db_data: