FROM python:3.12-slim

WORKDIR /app

COPY . .

# Устанавливаем netcat
RUN apt-get update && apt-get install -y netcat-openbsd && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir -r requirements.txt

RUN chmod +x ./start.sh

CMD ["./start.sh"]